// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: app.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const getApps = `-- name: GetApps :one
SELECT id, owner_id, name, description, settings, created_at, updated_at, subtitle FROM apps
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetApps(ctx context.Context, id uuid.UUID) (*Apps, error) {
	row := q.db.QueryRow(ctx, getApps, id)
	var i Apps
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.Description,
		&i.Settings,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Subtitle,
	)
	return &i, err
}
