// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package db

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Apps struct {
	ID          uuid.UUID          `db:"id" json:"id"`
	OwnerID     uuid.UUID          `db:"owner_id" json:"owner_id"`
	Name        string             `db:"name" json:"name"`
	Description *string            `db:"description" json:"description"`
	Settings    []byte             `db:"settings" json:"settings"`
	CreatedAt   pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	Subtitle    *string            `db:"subtitle" json:"subtitle"`
}
