// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	GetApps(ctx context.Context, id uuid.UUID) (*Apps, error)
}

var _ Querier = (*Queries)(nil)
