root = "."
testdata_dir = "testdata"
tmp_dir = "tmp"

[build]
args_bin = []
bin = "./tmp/main"
cmd = "go build -o ./tmp/main cmd/server/*.go"
delay = 500
exclude_dir = [
    "tmp",
    "dist",
    "vendor",
    "testdata",
    "resources",
    "node_modules",
]
exclude_file = []
exclude_regex = ["_test.go", "_templ.go"]
exclude_unchanged = false
follow_symlink = false
full_bin = ""
include_dir = ["assets", "cmd", "internal", "pkg", "view"]
include_ext = [
    "go",
    "tpl",
    "tmpl",
    "templ",
    "html",
    "css",
    "js",
]
include_file = []
kill_delay = "10s"
log = "build-errors.log"
poll = false
poll_interval = 0
post_cmd = []
pre_cmd = ["templ generate"]
rerun = false
rerun_delay = 500
send_interrupt = true
stop_on_error = false

[color]
app = ""
build = "yellow"
main = "magenta"
runner = "green"
watcher = "cyan"

[log]
main_only = false
time = false

[misc]
clean_on_exit = false

[screen]
clear_on_rebuild = false
keep_scroll = true
